### ISSUE TITLE
Add a new blog post or links in /about/ with these links

### ISSUE THREAD

**Issue by machikoyasuda** [maptimeLA/maptimela.github.io#1]
# Tutorials + Maps
- Leaflet & Mapbox Tutorial: https://github.com/maptimeLA/leaflet_mapbox_tut and corresponding Maps: http://maptimela.github.io/leaflet_mapbox_tut/index_mapbox.html http://maptimela.github.io/leaflet_mapbox_tut/index_leaflet.html
- SketchUp to Mapbox Tutorial: http://cityhubla.github.io/SketchupToMapboxJS/index_slide.html#0 http://cityhubla.github.io/SketchupToMapboxJS/
- Mapbox Studio 101 Tutorial: https://github.com/maptimeLA/mapbox_studio101 http://slides.com/omarureta/deck#/
- More Leaflet Tutorial: https://github.com/maptimeLA/git_your_map_here https://github.com/maptimeLA/git_your_map_here 
- D3 & QGIS Tutorial: https://github.com/maptimeLA/d3-foodpantries 
# Just a Map
- CicLAvia: http://maptimela.github.io/ciclavia_epic/
- LAPD Divisions: http://maptimela.github.io/lapd_divisions/
- Old LA Restaurants: http://maptimela.github.io/old-la-restaurants/
## How do I do this?!
- Either: Add a new Post, following the Jekyll page instructions

or 
- Add HTML into this file: https://github.com/maptimeLA/maptimela.github.io/blob/master/_site/about/index.html to update the /about/ page here http://maptimela.github.io/about/

**Comment by patriciarealini** [comment]
https://github.com/maptimeLA/projectshowcase/tree/master

**Comment by machikoyasuda** [comment]
# Super Serious Group Projects
1. \- http://jrhutson.github.io/Food-Resource-Map/ / https://github.com/maptimeLA/food_bank_data_bank
2. \- http://maptimela.github.io/old-la-restaurants/ / https://github.com/maptimeLA/old-la-restaurants
3. \- http://maptimela.github.io/GIS-Resources-Map/ / https://github.com/maptimeLA/GIS-Resources-Map

# Solo Projects
1. http://maptimela.github.io/ciclavia_epic/

# Demos
1. \- http://cityhubla.github.io/SketchupToMapboxJS/
2. \- http://maptimela.github.io/projectLA/
3. \- http://maptimela.github.io/leaflet_mapbox_tut/index_leaflet.html
4. \- http://maptimela.github.io/leaflet_mapbox_tut/index_mapbox.html
5. \- http://maptimela.github.io/maptime_bear/
6. \- http://maptimela.github.io/leaflet_simple_map/index_step2.html

# Maps with stuff on it
1. \- http://maptimela.github.io/neighborhoods/
2. \- http://maptimela.github.io/lapd_divisions/ / https://github.com/maptimeLA/lapd_divisions
3. \- http://maptimela.github.io/d3-foodpantries/step6/index.html / https://github.com/maptimeLA/d3-foodpantries
4. \- http://maptimela.github.io/mapstarter_lacounty/example/index.html / https://github.com/maptimeLA/mapstarter_lacounty
5. \- http://maptimela.github.io/git_your_map_here/

# Blank maps
1. \- http://maptimela.github.io/freshmap/
2. \- http://maptimela.github.io/mapstarter/

# Workshops
1. \- The OG Git / Leaflet tutorial https://github.com/maptimeLA/git_your_map_here
2. \- CartoDB http://maptimela.github.io/how-to-cartodb/#0 / https://github.com/maptimeLA/how-to-cartodb
3. \- SketchUp http://cityhubla.github.io/SketchupToMapboxJS/index_slide.html#0
4. \- Mapbox Studio https://github.com/maptimeLA/mapbox_studio101 / http://slides.com/omarureta/deck#/
5. \- D3 & QGIS https://github.com/maptimeLA/d3-foodpantries
6. \- QGIS & Leaflet https://github.com/maptimeLA/mapstarter_lacounty 
7. \- Leaflet & Mapbox https://github.com/maptimeLA/leaflet_mapbox_tut
8. \- OSM Data http://maptimela.github.io/osm_io/ / https://github.com/maptimeLA/osm_io
9. \- QGIS & SketchUp https://github.com/maptimeLA/qgis_sketchup
10. \- SketchUp https://github.com/maptimeLA/maptime_bear
11. \- QGIS & OpenData https://github.com/maptimeLA/qgis_opendata

**Comment by machikoyasuda** [comment]
1. \- http://jrhutson.github.io/Food-Resource-Map/ / https://github.com/maptimeLA/food_bank_data_bank
2. \- http://maptimela.github.io/old-la-restaurants/ / https://github.com/maptimeLA/old-la-restaurants
3. \- http://maptimela.github.io/GIS-Resources-Map/ / https://github.com/maptimeLA/GIS-Resources-Map
4. \- http://maptimela.github.io/ciclavia_epic/
5. \- http://cityhubla.github.io/SketchupToMapboxJS/
6. \- http://maptimela.github.io/projectLA/
7. \- http://maptimela.github.io/leaflet_mapbox_tut/index_leaflet.html
8. \- http://maptimela.github.io/leaflet_mapbox_tut/index_mapbox.html
9. \- http://maptimela.github.io/maptime_bear/
10. \- http://maptimela.github.io/leaflet_simple_map/index_step2.html
11. \- http://maptimela.github.io/neighborhoods/
12. \- http://maptimela.github.io/lapd_divisions/ / https://github.com/maptimeLA/lapd_divisions
13. \- http://maptimela.github.io/d3-foodpantries/step6/index.html / https://github.com/maptimeLA/d3-foodpantries
14. \- http://maptimela.github.io/mapstarter_lacounty/example/index.html / https://github.com/maptimeLA/mapstarter_lacounty
15. \- http://maptimela.github.io/git_your_map_here/
16. \- http://maptimela.github.io/freshmap/
17. \- http://maptimela.github.io/mapstarter/
18. \- The OG Git / Leaflet tutorial https://github.com/maptimeLA/git_your_map_here
19. \- CartoDB http://maptimela.github.io/how-to-cartodb/#0 / https://github.com/maptimeLA/how-to-cartodb
20. \- SketchUp http://cityhubla.github.io/SketchupToMapboxJS/index_slide.html#0
21. \- Mapbox Studio https://github.com/maptimeLA/mapbox_studio101 / http://slides.com/omarureta/deck#/
22. \- D3 & QGIS https://github.com/maptimeLA/d3-foodpantries
23. \- QGIS & Leaflet https://github.com/maptimeLA/mapstarter_lacounty 
24. \- Leaflet & Mapbox https://github.com/maptimeLA/leaflet_mapbox_tut
25. \- OSM Data http://maptimela.github.io/osm_io/ / https://github.com/maptimeLA/osm_io
26. \- QGIS & SketchUp https://github.com/maptimeLA/qgis_sketchup
27. \- SketchUp https://github.com/maptimeLA/maptime_bear
28. \- QGIS & OpenData https://github.com/maptimeLA/qgis_opendata

**Comment by machikoyasuda** [comment]
Closing this bc I just updated it: http://maptimela.github.io/about/
